"""Large idempotent demo catalog for EDUNOVA AI (skills, companies, roles)."""

SKILLS = [
    {"name": 'Python', "category": 'programming', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Java', "category": 'programming', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'C', "category": 'programming', "difficulty": 'beginner', "demand_indicator": 'medium'},
    {"name": 'C++', "category": 'programming', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'JavaScript', "category": 'programming', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'TypeScript', "category": 'programming', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Kotlin', "category": 'programming', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'Go', "category": 'programming', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'PHP', "category": 'programming', "difficulty": 'beginner', "demand_indicator": 'medium'},
    {"name": 'Rust', "category": 'programming', "difficulty": 'advanced', "demand_indicator": 'emerging'},
    {"name": 'Swift', "category": 'programming', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'R', "category": 'programming', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'Scala', "category": 'programming', "difficulty": 'advanced', "demand_indicator": 'medium'},
    {"name": 'DSA', "category": 'programming', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'OOP', "category": 'programming', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'System Design', "category": 'programming', "difficulty": 'advanced', "demand_indicator": 'high'},
    {"name": 'SQL', "category": 'data', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Advanced SQL', "category": 'data', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Excel', "category": 'data', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Pandas', "category": 'data', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'NumPy', "category": 'data', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Data Cleaning', "category": 'data', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Data Visualization', "category": 'data', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Statistics', "category": 'data', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Exploratory Data Analysis', "category": 'data', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Power BI', "category": 'data', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Tableau', "category": 'data', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Apache Spark', "category": 'data', "difficulty": 'advanced', "demand_indicator": 'medium'},
    {"name": 'Hadoop', "category": 'data', "difficulty": 'advanced', "demand_indicator": 'medium'},
    {"name": 'ETL', "category": 'data', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'Business Analytics', "category": 'data', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'A/B Testing', "category": 'data', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'Machine Learning', "category": 'ai_ml', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Deep Learning', "category": 'ai_ml', "difficulty": 'advanced', "demand_indicator": 'high'},
    {"name": 'NLP', "category": 'ai_ml', "difficulty": 'advanced', "demand_indicator": 'high'},
    {"name": 'Computer Vision', "category": 'ai_ml', "difficulty": 'advanced', "demand_indicator": 'medium'},
    {"name": 'Scikit-learn', "category": 'ai_ml', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'TensorFlow', "category": 'ai_ml', "difficulty": 'advanced', "demand_indicator": 'high'},
    {"name": 'PyTorch', "category": 'ai_ml', "difficulty": 'advanced', "demand_indicator": 'high'},
    {"name": 'Feature Engineering', "category": 'ai_ml', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Model Evaluation', "category": 'ai_ml', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Regression', "category": 'ai_ml', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Classification', "category": 'ai_ml', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Clustering', "category": 'ai_ml', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'Recommendation Systems', "category": 'ai_ml', "difficulty": 'advanced', "demand_indicator": 'medium'},
    {"name": 'Generative AI', "category": 'ai_ml', "difficulty": 'intermediate', "demand_indicator": 'emerging'},
    {"name": 'Prompt Engineering', "category": 'ai_ml', "difficulty": 'beginner', "demand_indicator": 'emerging'},
    {"name": 'MLOps', "category": 'ai_ml', "difficulty": 'advanced', "demand_indicator": 'emerging'},
    {"name": 'HTML', "category": 'web', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'CSS', "category": 'web', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Flask', "category": 'web', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Django', "category": 'web', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'REST APIs', "category": 'web', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Bootstrap', "category": 'web', "difficulty": 'beginner', "demand_indicator": 'medium'},
    {"name": 'React', "category": 'web', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Node.js', "category": 'web', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Next.js', "category": 'web', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'FastAPI', "category": 'web', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Vue.js', "category": 'web', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'Git', "category": 'cloud', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'GitHub', "category": 'cloud', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Docker', "category": 'cloud', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Linux', "category": 'cloud', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'AWS', "category": 'cloud', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Azure', "category": 'cloud', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Google Cloud', "category": 'cloud', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'CI/CD', "category": 'cloud', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Kubernetes', "category": 'cloud', "difficulty": 'advanced', "demand_indicator": 'high'},
    {"name": 'Terraform', "category": 'cloud', "difficulty": 'advanced', "demand_indicator": 'medium'},
    {"name": 'Communication', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Problem Solving', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Critical Thinking', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Teamwork', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Leadership', "category": 'professional', "difficulty": 'intermediate', "demand_indicator": 'medium'},
    {"name": 'Presentation', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Time Management', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Interview Skills', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'high'},
    {"name": 'Business Analysis', "category": 'professional', "difficulty": 'intermediate', "demand_indicator": 'high'},
    {"name": 'Agile', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'medium'},
    {"name": 'Scrum', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'medium'},
    {"name": 'Networking', "category": 'professional', "difficulty": 'beginner', "demand_indicator": 'medium'},
]

COMPANIES = [
    {"name": 'Microsoft', "slug": 'microsoft', "company_type": 'product', "industry": 'Technology', "headquarters": 'Redmond, USA', "competitiveness": 'high', "description": 'Microsoft is a well-known organization in Technology. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Redmond, USA'},
    {"name": 'Google', "slug": 'google', "company_type": 'product', "industry": 'Technology', "headquarters": 'Mountain View, USA', "competitiveness": 'high', "description": 'Google is a well-known organization in Technology. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Mountain View, USA'},
    {"name": 'Amazon', "slug": 'amazon', "company_type": 'product', "industry": 'E-commerce / Cloud', "headquarters": 'Seattle, USA', "competitiveness": 'high', "description": 'Amazon is a well-known organization in E-commerce / Cloud. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Seattle, USA'},
    {"name": 'Apple', "slug": 'apple', "company_type": 'product', "industry": 'Technology', "headquarters": 'Cupertino, USA', "competitiveness": 'high', "description": 'Apple is a well-known organization in Technology. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Cupertino, USA'},
    {"name": 'Meta', "slug": 'meta', "company_type": 'product', "industry": 'Technology', "headquarters": 'Menlo Park, USA', "competitiveness": 'high', "description": 'Meta is a well-known organization in Technology. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Menlo Park, USA'},
    {"name": 'IBM', "slug": 'ibm', "company_type": 'product', "industry": 'Technology / Consulting', "headquarters": 'Armonk, USA', "competitiveness": 'medium', "description": 'IBM is a well-known organization in Technology / Consulting. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Armonk, USA'},
    {"name": 'Oracle', "slug": 'oracle', "company_type": 'product', "industry": 'Enterprise Software', "headquarters": 'Austin, USA', "competitiveness": 'medium', "description": 'Oracle is a well-known organization in Enterprise Software. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Austin, USA'},
    {"name": 'Adobe', "slug": 'adobe', "company_type": 'product', "industry": 'Creative Software', "headquarters": 'San Jose, USA', "competitiveness": 'high', "description": 'Adobe is a well-known organization in Creative Software. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Jose, USA'},
    {"name": 'Salesforce', "slug": 'salesforce', "company_type": 'product', "industry": 'Enterprise SaaS', "headquarters": 'San Francisco, USA', "competitiveness": 'high', "description": 'Salesforce is a well-known organization in Enterprise SaaS. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'NVIDIA', "slug": 'nvidia', "company_type": 'product', "industry": 'Semiconductors / AI', "headquarters": 'Santa Clara, USA', "competitiveness": 'high', "description": 'NVIDIA is a well-known organization in Semiconductors / AI. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Santa Clara, USA'},
    {"name": 'Intel', "slug": 'intel', "company_type": 'product', "industry": 'Semiconductors', "headquarters": 'Santa Clara, USA', "competitiveness": 'medium', "description": 'Intel is a well-known organization in Semiconductors. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Santa Clara, USA'},
    {"name": 'Cisco', "slug": 'cisco', "company_type": 'product', "industry": 'Networking', "headquarters": 'San Jose, USA', "competitiveness": 'medium', "description": 'Cisco is a well-known organization in Networking. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Jose, USA'},
    {"name": 'Dell', "slug": 'dell', "company_type": 'product', "industry": 'Hardware', "headquarters": 'Round Rock, USA', "competitiveness": 'moderate', "description": 'Dell is a well-known organization in Hardware. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Round Rock, USA'},
    {"name": 'HP', "slug": 'hp', "company_type": 'product', "industry": 'Hardware', "headquarters": 'Palo Alto, USA', "competitiveness": 'moderate', "description": 'HP is a well-known organization in Hardware. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Palo Alto, USA'},
    {"name": 'Accenture', "slug": 'accenture', "company_type": 'consulting', "industry": 'IT Consulting', "headquarters": 'Dublin, Ireland', "competitiveness": 'medium', "description": 'Accenture is a well-known organization in IT Consulting. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Dublin, Ireland'},
    {"name": 'Deloitte', "slug": 'deloitte', "company_type": 'consulting', "industry": 'Professional Services', "headquarters": 'London, UK', "competitiveness": 'high', "description": 'Deloitte is a well-known organization in Professional Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'London, UK'},
    {"name": 'EY', "slug": 'ey', "company_type": 'consulting', "industry": 'Professional Services', "headquarters": 'London, UK', "competitiveness": 'high', "description": 'EY is a well-known organization in Professional Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'London, UK'},
    {"name": 'KPMG', "slug": 'kpmg', "company_type": 'consulting', "industry": 'Professional Services', "headquarters": 'Amstelveen, NL', "competitiveness": 'high', "description": 'KPMG is a well-known organization in Professional Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Amstelveen, NL'},
    {"name": 'PwC', "slug": 'pwc', "company_type": 'consulting', "industry": 'Professional Services', "headquarters": 'London, UK', "competitiveness": 'high', "description": 'PwC is a well-known organization in Professional Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'London, UK'},
    {"name": 'TCS', "slug": 'tcs', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Mumbai, India', "competitiveness": 'medium', "description": 'TCS is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Mumbai, India'},
    {"name": 'Infosys', "slug": 'infosys', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'Infosys is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Wipro', "slug": 'wipro', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'Wipro is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'HCLTech', "slug": 'hcltech', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Noida, India', "competitiveness": 'medium', "description": 'HCLTech is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Noida, India'},
    {"name": 'Tech Mahindra', "slug": 'tech-mahindra', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Pune, India', "competitiveness": 'medium', "description": 'Tech Mahindra is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Pune, India'},
    {"name": 'Cognizant', "slug": 'cognizant', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Teaneck, USA', "competitiveness": 'medium', "description": 'Cognizant is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Teaneck, USA'},
    {"name": 'Capgemini', "slug": 'capgemini', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Paris, France', "competitiveness": 'medium', "description": 'Capgemini is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Paris, France'},
    {"name": 'LTIMindtree', "slug": 'ltimindtree', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Mumbai, India', "competitiveness": 'medium', "description": 'LTIMindtree is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Mumbai, India'},
    {"name": 'Zoho', "slug": 'zoho', "company_type": 'product', "industry": 'SaaS', "headquarters": 'Chennai, India', "competitiveness": 'medium', "description": 'Zoho is a well-known organization in SaaS. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Chennai, India'},
    {"name": 'Freshworks', "slug": 'freshworks', "company_type": 'product', "industry": 'SaaS', "headquarters": 'San Mateo / Chennai', "competitiveness": 'medium', "description": 'Freshworks is a well-known organization in SaaS. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Mateo / Chennai'},
    {"name": 'Paytm', "slug": 'paytm', "company_type": 'product', "industry": 'Fintech', "headquarters": 'Noida, India', "competitiveness": 'medium', "description": 'Paytm is a well-known organization in Fintech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Noida, India'},
    {"name": 'PhonePe', "slug": 'phonepe', "company_type": 'product', "industry": 'Fintech', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'PhonePe is a well-known organization in Fintech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Flipkart', "slug": 'flipkart', "company_type": 'product', "industry": 'E-commerce', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'Flipkart is a well-known organization in E-commerce. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Walmart', "slug": 'walmart', "company_type": 'product', "industry": 'Retail', "headquarters": 'Bentonville, USA', "competitiveness": 'medium', "description": 'Walmart is a well-known organization in Retail. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bentonville, USA'},
    {"name": 'Uber', "slug": 'uber', "company_type": 'product', "industry": 'Mobility', "headquarters": 'San Francisco, USA', "competitiveness": 'high', "description": 'Uber is a well-known organization in Mobility. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'Airbnb', "slug": 'airbnb', "company_type": 'product', "industry": 'Travel Tech', "headquarters": 'San Francisco, USA', "competitiveness": 'high', "description": 'Airbnb is a well-known organization in Travel Tech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'JPMorgan Chase', "slug": 'jpmorgan-chase', "company_type": 'product', "industry": 'Financial Services', "headquarters": 'New York, USA', "competitiveness": 'high', "description": 'JPMorgan Chase is a well-known organization in Financial Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'New York, USA'},
    {"name": 'Goldman Sachs', "slug": 'goldman-sachs', "company_type": 'product', "industry": 'Financial Services', "headquarters": 'New York, USA', "competitiveness": 'high', "description": 'Goldman Sachs is a well-known organization in Financial Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'New York, USA'},
    {"name": 'Morgan Stanley', "slug": 'morgan-stanley', "company_type": 'product', "industry": 'Financial Services', "headquarters": 'New York, USA', "competitiveness": 'high', "description": 'Morgan Stanley is a well-known organization in Financial Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'New York, USA'},
    {"name": 'HSBC', "slug": 'hsbc', "company_type": 'product', "industry": 'Financial Services', "headquarters": 'London, UK', "competitiveness": 'medium', "description": 'HSBC is a well-known organization in Financial Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'London, UK'},
    {"name": 'Barclays', "slug": 'barclays', "company_type": 'product', "industry": 'Financial Services', "headquarters": 'London, UK', "competitiveness": 'medium', "description": 'Barclays is a well-known organization in Financial Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'London, UK'},
    {"name": 'Visa', "slug": 'visa', "company_type": 'product', "industry": 'Payments', "headquarters": 'San Francisco, USA', "competitiveness": 'high', "description": 'Visa is a well-known organization in Payments. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'Mastercard', "slug": 'mastercard', "company_type": 'product', "industry": 'Payments', "headquarters": 'Purchase, USA', "competitiveness": 'high', "description": 'Mastercard is a well-known organization in Payments. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Purchase, USA'},
    {"name": 'Netflix', "slug": 'netflix', "company_type": 'product', "industry": 'Media', "headquarters": 'Los Gatos, USA', "competitiveness": 'high', "description": 'Netflix is a well-known organization in Media. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Los Gatos, USA'},
    {"name": 'Spotify', "slug": 'spotify', "company_type": 'product', "industry": 'Media', "headquarters": 'Stockholm, Sweden', "competitiveness": 'high', "description": 'Spotify is a well-known organization in Media. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Stockholm, Sweden'},
    {"name": 'LinkedIn', "slug": 'linkedin', "company_type": 'product', "industry": 'Technology', "headquarters": 'Sunnyvale, USA', "competitiveness": 'high', "description": 'LinkedIn is a well-known organization in Technology. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Sunnyvale, USA'},
    {"name": 'Samsung', "slug": 'samsung', "company_type": 'product', "industry": 'Electronics', "headquarters": 'Suwon, South Korea', "competitiveness": 'medium', "description": 'Samsung is a well-known organization in Electronics. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Suwon, South Korea'},
    {"name": 'Sony', "slug": 'sony', "company_type": 'product', "industry": 'Electronics', "headquarters": 'Tokyo, Japan', "competitiveness": 'medium', "description": 'Sony is a well-known organization in Electronics. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Tokyo, Japan'},
    {"name": 'Qualcomm', "slug": 'qualcomm', "company_type": 'product', "industry": 'Semiconductors', "headquarters": 'San Diego, USA', "competitiveness": 'high', "description": 'Qualcomm is a well-known organization in Semiconductors. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Diego, USA'},
    {"name": 'Broadcom', "slug": 'broadcom', "company_type": 'product', "industry": 'Semiconductors', "headquarters": 'San Jose, USA', "competitiveness": 'high', "description": 'Broadcom is a well-known organization in Semiconductors. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Jose, USA'},
    {"name": 'ServiceNow', "slug": 'servicenow', "company_type": 'product', "industry": 'Enterprise SaaS', "headquarters": 'Santa Clara, USA', "competitiveness": 'high', "description": 'ServiceNow is a well-known organization in Enterprise SaaS. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Santa Clara, USA'},
    {"name": 'Workday', "slug": 'workday', "company_type": 'product', "industry": 'Enterprise SaaS', "headquarters": 'Pleasanton, USA', "competitiveness": 'medium', "description": 'Workday is a well-known organization in Enterprise SaaS. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Pleasanton, USA'},
    {"name": 'Intuit', "slug": 'intuit', "company_type": 'product', "industry": 'Fintech / Software', "headquarters": 'Mountain View, USA', "competitiveness": 'medium', "description": 'Intuit is a well-known organization in Fintech / Software. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Mountain View, USA'},
    {"name": 'Atlassian', "slug": 'atlassian', "company_type": 'product', "industry": 'Developer Tools', "headquarters": 'Sydney, Australia', "competitiveness": 'medium', "description": 'Atlassian is a well-known organization in Developer Tools. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Sydney, Australia'},
    {"name": 'Shopify', "slug": 'shopify', "company_type": 'product', "industry": 'E-commerce', "headquarters": 'Ottawa, Canada', "competitiveness": 'medium', "description": 'Shopify is a well-known organization in E-commerce. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Ottawa, Canada'},
    {"name": 'Stripe', "slug": 'stripe', "company_type": 'product', "industry": 'Fintech', "headquarters": 'San Francisco, USA', "competitiveness": 'high', "description": 'Stripe is a well-known organization in Fintech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'Block', "slug": 'block', "company_type": 'product', "industry": 'Fintech', "headquarters": 'San Francisco, USA', "competitiveness": 'medium', "description": 'Block is a well-known organization in Fintech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'PayPal', "slug": 'paypal', "company_type": 'product', "industry": 'Fintech', "headquarters": 'San Jose, USA', "competitiveness": 'medium', "description": 'PayPal is a well-known organization in Fintech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Jose, USA'},
    {"name": 'Booking.com', "slug": 'booking-com', "company_type": 'product', "industry": 'Travel Tech', "headquarters": 'Amsterdam, NL', "competitiveness": 'medium', "description": 'Booking.com is a well-known organization in Travel Tech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Amsterdam, NL'},
    {"name": 'Expedia', "slug": 'expedia', "company_type": 'product', "industry": 'Travel Tech', "headquarters": 'Seattle, USA', "competitiveness": 'medium', "description": 'Expedia is a well-known organization in Travel Tech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Seattle, USA'},
    {"name": 'Tesla', "slug": 'tesla', "company_type": 'product', "industry": 'Automotive / Energy', "headquarters": 'Austin, USA', "competitiveness": 'high', "description": 'Tesla is a well-known organization in Automotive / Energy. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Austin, USA'},
    {"name": 'Boeing', "slug": 'boeing', "company_type": 'product', "industry": 'Aerospace', "headquarters": 'Arlington, USA', "competitiveness": 'medium', "description": 'Boeing is a well-known organization in Aerospace. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Arlington, USA'},
    {"name": 'Siemens', "slug": 'siemens', "company_type": 'product', "industry": 'Industrial Tech', "headquarters": 'Munich, Germany', "competitiveness": 'medium', "description": 'Siemens is a well-known organization in Industrial Tech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Munich, Germany'},
    {"name": 'SAP', "slug": 'sap', "company_type": 'product', "industry": 'Enterprise Software', "headquarters": 'Walldorf, Germany', "competitiveness": 'medium', "description": 'SAP is a well-known organization in Enterprise Software. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Walldorf, Germany'},
    {"name": 'VMware', "slug": 'vmware', "company_type": 'product', "industry": 'Cloud Infrastructure', "headquarters": 'Palo Alto, USA', "competitiveness": 'medium', "description": 'VMware is a well-known organization in Cloud Infrastructure. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Palo Alto, USA'},
    {"name": 'Red Hat', "slug": 'red-hat', "company_type": 'product', "industry": 'Open Source / Cloud', "headquarters": 'Raleigh, USA', "competitiveness": 'medium', "description": 'Red Hat is a well-known organization in Open Source / Cloud. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Raleigh, USA'},
    {"name": 'MongoDB', "slug": 'mongodb', "company_type": 'product', "industry": 'Data Platform', "headquarters": 'New York, USA', "competitiveness": 'medium', "description": 'MongoDB is a well-known organization in Data Platform. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'New York, USA'},
    {"name": 'Snowflake', "slug": 'snowflake', "company_type": 'product', "industry": 'Data Cloud', "headquarters": 'Bozeman, USA', "competitiveness": 'high', "description": 'Snowflake is a well-known organization in Data Cloud. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bozeman, USA'},
    {"name": 'Databricks', "slug": 'databricks', "company_type": 'product', "industry": 'Data / AI', "headquarters": 'San Francisco, USA', "competitiveness": 'high', "description": 'Databricks is a well-known organization in Data / AI. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'Palantir', "slug": 'palantir', "company_type": 'product', "industry": 'Data Analytics', "headquarters": 'Denver, USA', "competitiveness": 'high', "description": 'Palantir is a well-known organization in Data Analytics. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Denver, USA'},
    {"name": 'Canva', "slug": 'canva', "company_type": 'product', "industry": 'Creative Software', "headquarters": 'Sydney, Australia', "competitiveness": 'medium', "description": 'Canva is a well-known organization in Creative Software. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Sydney, Australia'},
    {"name": 'Notion', "slug": 'notion', "company_type": 'product', "industry": 'Productivity', "headquarters": 'San Francisco, USA', "competitiveness": 'medium', "description": 'Notion is a well-known organization in Productivity. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'Slack', "slug": 'slack', "company_type": 'product', "industry": 'Collaboration', "headquarters": 'San Francisco, USA', "competitiveness": 'medium', "description": 'Slack is a well-known organization in Collaboration. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'Dropbox', "slug": 'dropbox', "company_type": 'product', "industry": 'Cloud Storage', "headquarters": 'San Francisco, USA', "competitiveness": 'medium', "description": 'Dropbox is a well-known organization in Cloud Storage. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'Cloudflare', "slug": 'cloudflare', "company_type": 'product', "industry": 'Internet Infrastructure', "headquarters": 'San Francisco, USA', "competitiveness": 'medium', "description": 'Cloudflare is a well-known organization in Internet Infrastructure. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'DigitalOcean', "slug": 'digitalocean', "company_type": 'product', "industry": 'Cloud', "headquarters": 'New York, USA', "competitiveness": 'moderate', "description": 'DigitalOcean is a well-known organization in Cloud. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'New York, USA'},
    {"name": 'HashiCorp', "slug": 'hashicorp', "company_type": 'product', "industry": 'DevOps', "headquarters": 'San Francisco, USA', "competitiveness": 'medium', "description": 'HashiCorp is a well-known organization in DevOps. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'GitLab', "slug": 'gitlab', "company_type": 'product', "industry": 'DevOps', "headquarters": 'Remote', "competitiveness": 'medium', "description": 'GitLab is a well-known organization in DevOps. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Remote'},
    {"name": 'Unity', "slug": 'unity', "company_type": 'product', "industry": 'Gaming / 3D', "headquarters": 'San Francisco, USA', "competitiveness": 'medium', "description": 'Unity is a well-known organization in Gaming / 3D. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Francisco, USA'},
    {"name": 'Epic Games', "slug": 'epic-games', "company_type": 'product', "industry": 'Gaming', "headquarters": 'Cary, USA', "competitiveness": 'high', "description": 'Epic Games is a well-known organization in Gaming. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Cary, USA'},
    {"name": 'Thoughtworks', "slug": 'thoughtworks', "company_type": 'consulting', "industry": 'Technology Consulting', "headquarters": 'Chicago, USA', "competitiveness": 'medium', "description": 'Thoughtworks is a well-known organization in Technology Consulting. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Chicago, USA'},
    {"name": 'McKinsey', "slug": 'mckinsey', "company_type": 'consulting', "industry": 'Management Consulting', "headquarters": 'New York, USA', "competitiveness": 'high', "description": 'McKinsey is a well-known organization in Management Consulting. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'New York, USA'},
    {"name": 'BCG', "slug": 'bcg', "company_type": 'consulting', "industry": 'Management Consulting', "headquarters": 'Boston, USA', "competitiveness": 'high', "description": 'BCG is a well-known organization in Management Consulting. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Boston, USA'},
    {"name": 'Bain', "slug": 'bain', "company_type": 'consulting', "industry": 'Management Consulting', "headquarters": 'Boston, USA', "competitiveness": 'high', "description": 'Bain is a well-known organization in Management Consulting. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Boston, USA'},
    {"name": 'Publicis Sapient', "slug": 'publicis-sapient', "company_type": 'consulting', "industry": 'Digital Consulting', "headquarters": 'Boston, USA', "competitiveness": 'medium', "description": 'Publicis Sapient is a well-known organization in Digital Consulting. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Boston, USA'},
    {"name": 'Genpact', "slug": 'genpact', "company_type": 'service', "industry": 'Business Process / Analytics', "headquarters": 'New York, USA', "competitiveness": 'moderate', "description": 'Genpact is a well-known organization in Business Process / Analytics. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'New York, USA'},
    {"name": 'Mu Sigma', "slug": 'mu-sigma', "company_type": 'service', "industry": 'Analytics', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'Mu Sigma is a well-known organization in Analytics. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Fractal Analytics', "slug": 'fractal-analytics', "company_type": 'service', "industry": 'Analytics', "headquarters": 'Mumbai, India', "competitiveness": 'medium', "description": 'Fractal Analytics is a well-known organization in Analytics. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Mumbai, India'},
    {"name": 'Tiger Analytics', "slug": 'tiger-analytics', "company_type": 'service', "industry": 'Analytics', "headquarters": 'Santa Clara / Chennai', "competitiveness": 'medium', "description": 'Tiger Analytics is a well-known organization in Analytics. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Santa Clara / Chennai'},
    {"name": 'Mphasis', "slug": 'mphasis', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Bengaluru, India', "competitiveness": 'moderate', "description": 'Mphasis is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Persistent Systems', "slug": 'persistent-systems', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Pune, India', "competitiveness": 'moderate', "description": 'Persistent Systems is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Pune, India'},
    {"name": 'Hexaware', "slug": 'hexaware', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Navi Mumbai, India', "competitiveness": 'moderate', "description": 'Hexaware is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Navi Mumbai, India'},
    {"name": 'Coforge', "slug": 'coforge', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Noida, India', "competitiveness": 'moderate', "description": 'Coforge is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Noida, India'},
    {"name": 'Zensar', "slug": 'zensar', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Pune, India', "competitiveness": 'moderate', "description": 'Zensar is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Pune, India'},
    {"name": 'Virtusa', "slug": 'virtusa', "company_type": 'service', "industry": 'IT Services', "headquarters": 'Southborough, USA', "competitiveness": 'moderate', "description": 'Virtusa is a well-known organization in IT Services. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Southborough, USA'},
    {"name": 'Reliance Jio', "slug": 'reliance-jio', "company_type": 'product', "industry": 'Telecom / Digital', "headquarters": 'Mumbai, India', "competitiveness": 'medium', "description": 'Reliance Jio is a well-known organization in Telecom / Digital. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Mumbai, India'},
    {"name": 'Swiggy', "slug": 'swiggy', "company_type": 'product', "industry": 'Consumer Tech', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'Swiggy is a well-known organization in Consumer Tech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Zomato', "slug": 'zomato', "company_type": 'product', "industry": 'Consumer Tech', "headquarters": 'Gurugram, India', "competitiveness": 'medium', "description": 'Zomato is a well-known organization in Consumer Tech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Gurugram, India'},
    {"name": 'Ola', "slug": 'ola', "company_type": 'product', "industry": 'Mobility', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'Ola is a well-known organization in Mobility. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Razorpay', "slug": 'razorpay', "company_type": 'product', "industry": 'Fintech', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'Razorpay is a well-known organization in Fintech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'CRED', "slug": 'cred', "company_type": 'product', "industry": 'Fintech', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'CRED is a well-known organization in Fintech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Groww', "slug": 'groww', "company_type": 'product', "industry": 'Fintech', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'Groww is a well-known organization in Fintech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Zerodha', "slug": 'zerodha', "company_type": 'product', "industry": 'Fintech', "headquarters": 'Bengaluru, India', "competitiveness": 'medium', "description": 'Zerodha is a well-known organization in Fintech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'MakeMyTrip', "slug": 'makemytrip', "company_type": 'product', "industry": 'Travel Tech', "headquarters": 'Gurugram, India', "competitiveness": 'moderate', "description": 'MakeMyTrip is a well-known organization in Travel Tech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Gurugram, India'},
    {"name": 'Infosys BPM', "slug": 'infosys-bpm', "company_type": 'service', "industry": 'BPM', "headquarters": 'Bengaluru, India', "competitiveness": 'moderate', "description": 'Infosys BPM is a well-known organization in BPM. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Bengaluru, India'},
    {"name": 'Dell Technologies', "slug": 'dell-technologies', "company_type": 'product', "industry": 'Hardware / IT', "headquarters": 'Round Rock, USA', "competitiveness": 'moderate', "description": 'Dell Technologies is a well-known organization in Hardware / IT. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Round Rock, USA'},
    {"name": 'Cisco Systems', "slug": 'cisco-systems', "company_type": 'product', "industry": 'Networking', "headquarters": 'San Jose, USA', "competitiveness": 'medium', "description": 'Cisco Systems is a well-known organization in Networking. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Jose, USA'},
    {"name": 'Oracle NetSuite', "slug": 'oracle-netsuite', "company_type": 'product', "industry": 'Enterprise SaaS', "headquarters": 'Austin, USA', "competitiveness": 'medium', "description": 'Oracle NetSuite is a well-known organization in Enterprise SaaS. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Austin, USA'},
    {"name": 'Yahoo', "slug": 'yahoo', "company_type": 'product', "industry": 'Media / Tech', "headquarters": 'New York, USA', "competitiveness": 'moderate', "description": 'Yahoo is a well-known organization in Media / Tech. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'New York, USA'},
    {"name": 'eBay', "slug": 'ebay', "company_type": 'product', "industry": 'E-commerce', "headquarters": 'San Jose, USA', "competitiveness": 'medium', "description": 'eBay is a well-known organization in E-commerce. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'San Jose, USA'},
    {"name": 'Intel Corporation', "slug": 'intel-corporation', "company_type": 'product', "industry": 'Semiconductors', "headquarters": 'Santa Clara, USA', "competitiveness": 'medium', "description": 'Intel Corporation is a well-known organization in Semiconductors. Catalog entry for educational compatibility estimates only — not live openings or salary data.', "country_focus": 'Santa Clara, USA'},
]

CAREER_ROLES = [
    {"name": 'Data Analyst', "category": 'analytics', "description": 'Analyze data to support decisions using SQL, visualization, and statistics.'},
    {"name": 'Data Scientist', "category": 'analytics', "description": 'Build predictive models and extract insights from complex datasets.'},
    {"name": 'Machine Learning Engineer', "category": 'ai', "description": 'Productionize ML models with strong software and ML fundamentals.'},
    {"name": 'AI Engineer', "category": 'ai', "description": 'Design and integrate AI systems including generative and classical ML.'},
    {"name": 'Software Engineer', "category": 'engineering', "description": 'Design, build, and maintain reliable software systems.'},
    {"name": 'Backend Developer', "category": 'engineering', "description": 'Build APIs, services, and data layers for applications.'},
    {"name": 'Frontend Developer', "category": 'engineering', "description": 'Build accessible, responsive user interfaces.'},
    {"name": 'Full Stack Developer', "category": 'engineering', "description": 'Deliver end-to-end web features across frontend and backend.'},
    {"name": 'Business Analyst', "category": 'business', "description": 'Bridge business needs and technology with requirements and analysis.'},
    {"name": 'Product Analyst', "category": 'analytics', "description": 'Measure product performance and recommend data-backed improvements.'},
    {"name": 'BI Analyst', "category": 'analytics', "description": 'Build dashboards and reporting for business stakeholders.'},
    {"name": 'Data Engineer', "category": 'engineering', "description": 'Design pipelines and reliable data platforms.'},
    {"name": 'Cloud Engineer', "category": 'engineering', "description": 'Build and operate cloud infrastructure securely.'},
    {"name": 'DevOps Engineer', "category": 'engineering', "description": 'Automate delivery pipelines and improve reliability.'},
    {"name": 'Cybersecurity Analyst', "category": 'security', "description": 'Protect systems through monitoring, analysis, and hardening.'},
    {"name": 'NLP Engineer', "category": 'ai', "description": 'Build language understanding and generation systems.'},
    {"name": 'Computer Vision Engineer', "category": 'ai', "description": 'Build models that interpret images and video.'},
    {"name": 'MLOps Engineer', "category": 'ai', "description": 'Operate ML systems in production with monitoring and CI/CD.'},
    {"name": 'Product Manager', "category": 'business', "description": 'Define product direction and coordinate delivery.'},
    {"name": 'UX/UI Designer', "category": 'design', "description": 'Design usable interfaces and user experiences.'},
]

ROLE_SKILLS = {
    'Data Analyst': [
        {"skill": 'Python', "required_level": 3, "importance": 1.1},
        {"skill": 'SQL', "required_level": 4, "importance": 1.3},
        {"skill": 'Advanced SQL', "required_level": 3, "importance": 1.2},
        {"skill": 'Excel', "required_level": 3, "importance": 1.0},
        {"skill": 'Pandas', "required_level": 3, "importance": 1.1},
        {"skill": 'Statistics', "required_level": 3, "importance": 1.1},
        {"skill": 'Data Visualization', "required_level": 3, "importance": 1.0},
        {"skill": 'Power BI', "required_level": 3, "importance": 1.0},
        {"skill": 'Tableau', "required_level": 2, "importance": 0.8},
        {"skill": 'Communication', "required_level": 3, "importance": 0.9},
        {"skill": 'Business Analytics', "required_level": 3, "importance": 1.0},
    ],
    'Data Scientist': [
        {"skill": 'Python', "required_level": 4, "importance": 1.3},
        {"skill": 'SQL', "required_level": 3, "importance": 1.1},
        {"skill": 'Pandas', "required_level": 4, "importance": 1.2},
        {"skill": 'NumPy', "required_level": 3, "importance": 1.1},
        {"skill": 'Statistics', "required_level": 4, "importance": 1.3},
        {"skill": 'Machine Learning', "required_level": 4, "importance": 1.3},
        {"skill": 'Scikit-learn', "required_level": 4, "importance": 1.2},
        {"skill": 'Feature Engineering', "required_level": 3, "importance": 1.1},
        {"skill": 'Model Evaluation', "required_level": 3, "importance": 1.1},
        {"skill": 'Data Visualization', "required_level": 3, "importance": 1.0},
    ],
    'Machine Learning Engineer': [
        {"skill": 'Python', "required_level": 4, "importance": 1.3},
        {"skill": 'Machine Learning', "required_level": 4, "importance": 1.3},
        {"skill": 'Deep Learning', "required_level": 3, "importance": 1.1},
        {"skill": 'Scikit-learn', "required_level": 3, "importance": 1.0},
        {"skill": 'Docker', "required_level": 3, "importance": 1.1},
        {"skill": 'REST APIs', "required_level": 3, "importance": 1.0},
        {"skill": 'SQL', "required_level": 3, "importance": 1.0},
        {"skill": 'MLOps', "required_level": 3, "importance": 1.1},
        {"skill": 'Git', "required_level": 3, "importance": 0.9},
    ],
    'AI Engineer': [
        {"skill": 'Python', "required_level": 4, "importance": 1.3},
        {"skill": 'Machine Learning', "required_level": 4, "importance": 1.2},
        {"skill": 'Deep Learning', "required_level": 4, "importance": 1.2},
        {"skill": 'NLP', "required_level": 3, "importance": 1.1},
        {"skill": 'Generative AI', "required_level": 3, "importance": 1.1},
        {"skill": 'PyTorch', "required_level": 3, "importance": 1.1},
        {"skill": 'REST APIs', "required_level": 3, "importance": 1.0},
        {"skill": 'Prompt Engineering', "required_level": 3, "importance": 0.9},
    ],
    'Software Engineer': [
        {"skill": 'Python', "required_level": 3, "importance": 1.0},
        {"skill": 'Java', "required_level": 3, "importance": 1.0},
        {"skill": 'DSA', "required_level": 4, "importance": 1.3},
        {"skill": 'OOP', "required_level": 4, "importance": 1.2},
        {"skill": 'SQL', "required_level": 3, "importance": 1.0},
        {"skill": 'Git', "required_level": 3, "importance": 1.0},
        {"skill": 'REST APIs', "required_level": 3, "importance": 1.1},
        {"skill": 'System Design', "required_level": 3, "importance": 1.1},
        {"skill": 'Linux', "required_level": 2, "importance": 0.8},
    ],
    'Backend Developer': [
        {"skill": 'Python', "required_level": 4, "importance": 1.2},
        {"skill": 'Java', "required_level": 3, "importance": 1.0},
        {"skill": 'SQL', "required_level": 4, "importance": 1.2},
        {"skill": 'REST APIs', "required_level": 4, "importance": 1.3},
        {"skill": 'Docker', "required_level": 3, "importance": 1.0},
        {"skill": 'Git', "required_level": 3, "importance": 1.0},
        {"skill": 'Linux', "required_level": 3, "importance": 1.0},
        {"skill": 'System Design', "required_level": 3, "importance": 1.1},
    ],
    'Frontend Developer': [
        {"skill": 'HTML', "required_level": 4, "importance": 1.2},
        {"skill": 'CSS', "required_level": 4, "importance": 1.2},
        {"skill": 'JavaScript', "required_level": 4, "importance": 1.3},
        {"skill": 'React', "required_level": 4, "importance": 1.2},
        {"skill": 'TypeScript', "required_level": 3, "importance": 1.0},
        {"skill": 'Git', "required_level": 3, "importance": 0.9},
    ],
    'Full Stack Developer': [
        {"skill": 'HTML', "required_level": 3, "importance": 1.0},
        {"skill": 'CSS', "required_level": 3, "importance": 1.0},
        {"skill": 'JavaScript', "required_level": 4, "importance": 1.2},
        {"skill": 'React', "required_level": 3, "importance": 1.1},
        {"skill": 'Flask', "required_level": 3, "importance": 1.0},
        {"skill": 'SQL', "required_level": 3, "importance": 1.1},
        {"skill": 'REST APIs', "required_level": 4, "importance": 1.2},
        {"skill": 'Git', "required_level": 3, "importance": 1.0},
    ],
    'Business Analyst': [
        {"skill": 'Excel', "required_level": 4, "importance": 1.2},
        {"skill": 'SQL', "required_level": 3, "importance": 1.1},
        {"skill": 'Communication', "required_level": 4, "importance": 1.2},
        {"skill": 'Business Analysis', "required_level": 4, "importance": 1.3},
        {"skill": 'Presentation', "required_level": 3, "importance": 1.0},
        {"skill": 'Power BI', "required_level": 3, "importance": 1.0},
        {"skill": 'Critical Thinking', "required_level": 3, "importance": 1.0},
    ],
    'Product Analyst': [
        {"skill": 'SQL', "required_level": 4, "importance": 1.2},
        {"skill": 'Python', "required_level": 3, "importance": 1.0},
        {"skill": 'Statistics', "required_level": 3, "importance": 1.1},
        {"skill": 'A/B Testing', "required_level": 3, "importance": 1.1},
        {"skill": 'Data Visualization', "required_level": 3, "importance": 1.0},
        {"skill": 'Communication', "required_level": 3, "importance": 1.0},
    ],
    'BI Analyst': [
        {"skill": 'SQL', "required_level": 4, "importance": 1.2},
        {"skill": 'Power BI', "required_level": 4, "importance": 1.3},
        {"skill": 'Tableau', "required_level": 3, "importance": 1.1},
        {"skill": 'Excel', "required_level": 3, "importance": 1.0},
        {"skill": 'Data Visualization', "required_level": 4, "importance": 1.2},
        {"skill": 'Business Analytics', "required_level": 3, "importance": 1.0},
    ],
    'Data Engineer': [
        {"skill": 'Python', "required_level": 4, "importance": 1.2},
        {"skill": 'SQL', "required_level": 4, "importance": 1.3},
        {"skill": 'ETL', "required_level": 4, "importance": 1.2},
        {"skill": 'Apache Spark', "required_level": 3, "importance": 1.1},
        {"skill": 'Docker', "required_level": 3, "importance": 1.0},
        {"skill": 'AWS', "required_level": 3, "importance": 1.0},
        {"skill": 'Linux', "required_level": 3, "importance": 1.0},
    ],
    'Cloud Engineer': [
        {"skill": 'Linux', "required_level": 4, "importance": 1.2},
        {"skill": 'AWS', "required_level": 4, "importance": 1.3},
        {"skill": 'Docker', "required_level": 3, "importance": 1.1},
        {"skill": 'CI/CD', "required_level": 3, "importance": 1.1},
        {"skill": 'Terraform', "required_level": 3, "importance": 1.1},
        {"skill": 'Python', "required_level": 3, "importance": 0.9},
    ],
    'DevOps Engineer': [
        {"skill": 'Linux', "required_level": 4, "importance": 1.2},
        {"skill": 'Docker', "required_level": 4, "importance": 1.2},
        {"skill": 'CI/CD', "required_level": 4, "importance": 1.3},
        {"skill": 'Kubernetes', "required_level": 3, "importance": 1.1},
        {"skill": 'Git', "required_level": 3, "importance": 1.0},
        {"skill": 'AWS', "required_level": 3, "importance": 1.0},
    ],
    'Cybersecurity Analyst': [
        {"skill": 'Linux', "required_level": 3, "importance": 1.1},
        {"skill": 'Networking', "required_level": 4, "importance": 1.2},
        {"skill": 'Python', "required_level": 3, "importance": 1.0},
        {"skill": 'Critical Thinking', "required_level": 3, "importance": 1.0},
        {"skill": 'Problem Solving', "required_level": 3, "importance": 1.0},
    ],
    'NLP Engineer': [
        {"skill": 'Python', "required_level": 4, "importance": 1.3},
        {"skill": 'NLP', "required_level": 4, "importance": 1.3},
        {"skill": 'Machine Learning', "required_level": 4, "importance": 1.2},
        {"skill": 'Deep Learning', "required_level": 3, "importance": 1.1},
        {"skill": 'PyTorch', "required_level": 3, "importance": 1.1},
    ],
    'Computer Vision Engineer': [
        {"skill": 'Python', "required_level": 4, "importance": 1.3},
        {"skill": 'Computer Vision', "required_level": 4, "importance": 1.3},
        {"skill": 'Deep Learning', "required_level": 4, "importance": 1.2},
        {"skill": 'PyTorch', "required_level": 3, "importance": 1.1},
        {"skill": 'NumPy', "required_level": 3, "importance": 1.0},
    ],
    'MLOps Engineer': [
        {"skill": 'Python', "required_level": 4, "importance": 1.2},
        {"skill": 'MLOps', "required_level": 4, "importance": 1.3},
        {"skill": 'Docker', "required_level": 4, "importance": 1.2},
        {"skill": 'CI/CD', "required_level": 4, "importance": 1.2},
        {"skill": 'Kubernetes', "required_level": 3, "importance": 1.1},
        {"skill": 'Machine Learning', "required_level": 3, "importance": 1.1},
    ],
    'Product Manager': [
        {"skill": 'Communication', "required_level": 4, "importance": 1.3},
        {"skill": 'Presentation', "required_level": 4, "importance": 1.2},
        {"skill": 'Business Analysis', "required_level": 3, "importance": 1.1},
        {"skill": 'Critical Thinking', "required_level": 4, "importance": 1.2},
        {"skill": 'Leadership', "required_level": 3, "importance": 1.0},
        {"skill": 'Agile', "required_level": 3, "importance": 1.0},
    ],
    'UX/UI Designer': [
        {"skill": 'HTML', "required_level": 2, "importance": 0.8},
        {"skill": 'CSS', "required_level": 3, "importance": 1.0},
        {"skill": 'Communication', "required_level": 4, "importance": 1.2},
        {"skill": 'Presentation', "required_level": 4, "importance": 1.2},
        {"skill": 'Critical Thinking', "required_level": 3, "importance": 1.0},
    ],
}

ROADMAP_TEMPLATES = {
    'Data Analyst': ['Python fundamentals', 'SQL essentials', 'Excel for analysis', 'Statistics basics', 'Pandas and NumPy', 'Data visualization', 'Power BI / Tableau', 'Portfolio projects', 'Resume polish', 'Interview preparation'],
    'Data Scientist': ['Python for data science', 'Statistics and probability', 'Pandas / NumPy', 'Visualization', 'Machine learning foundations', 'Feature engineering', 'Model evaluation', 'End-to-end projects', 'Lightweight deployment', 'Interview prep'],
    'AI Engineer': ['Python and math refresh', 'Machine learning', 'Deep learning', 'NLP foundations', 'Computer vision intro', 'APIs for models', 'Deployment basics', 'MLOps awareness', 'Portfolio projects', 'Interview prep'],
    'Machine Learning Engineer': ['Strong Python', 'Classical ML', 'Model packaging', 'APIs', 'Docker', 'Evaluation in production', 'Monitoring basics', 'Projects', 'System design for ML', 'Interview prep'],
    'Software Engineer': ['Core programming', 'DSA practice', 'OOP', 'Databases / SQL', 'Git workflows', 'Backend fundamentals', 'REST APIs', 'System design intro', 'Projects', 'Interview prep'],
    'Full Stack Developer': ['HTML/CSS', 'JavaScript', 'Frontend framework', 'Backend API', 'Databases', 'Auth basics', 'Deployment', 'Projects', 'Git collaboration', 'Interview prep'],
    'Business Analyst': ['Business analysis fundamentals', 'Excel', 'SQL for BA', 'Requirements writing', 'Stakeholder communication', 'Dashboards', 'Case practice', 'Resume', 'Interview prep', 'Domain research'],
    'DevOps Engineer': ['Linux fundamentals', 'Git', 'CI/CD concepts', 'Docker', 'Cloud basics', 'Infrastructure as code intro', 'Monitoring awareness', 'Projects', 'Interview prep', 'Security basics'],
}

# Counts: skills=81 companies=110 roles=20
